# Generated by Django 4.0.5 on 2022-06-11 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bread',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=1500)),
                ('qty', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bread',
            },
        ),
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=1500)),
                ('qty', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cheese',
            },
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=1500)),
                ('qty', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sauce',
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=1500)),
                ('qty', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'topping',
            },
        ),
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('bread', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bread')),
                ('cheese', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cheese')),
                ('sauce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sauce')),
                ('topping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.topping')),
            ],
            options={
                'db_table': 'sandwich',
            },
        ),
    ]
