# Generated by Django 4.0.5 on 2022-06-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandwich',
            name='bread',
        ),
        migrations.AddField(
            model_name='sandwich',
            name='bread',
            field=models.ManyToManyField(to='api.bread'),
        ),
        migrations.RemoveField(
            model_name='sandwich',
            name='cheese',
        ),
        migrations.AddField(
            model_name='sandwich',
            name='cheese',
            field=models.ManyToManyField(to='api.cheese'),
        ),
        migrations.RemoveField(
            model_name='sandwich',
            name='sauce',
        ),
        migrations.AddField(
            model_name='sandwich',
            name='sauce',
            field=models.ManyToManyField(to='api.sauce'),
        ),
        migrations.RemoveField(
            model_name='sandwich',
            name='topping',
        ),
        migrations.AddField(
            model_name='sandwich',
            name='topping',
            field=models.ManyToManyField(to='api.topping'),
        ),
    ]
